from typing import Protocol

from app.models.stock import CompanyProfile, Event, FinancialSummary, PriceDaily


class StockRepository(Protocol):
    def init_db(self) -> None: ...

    def ping(self) -> bool: ...

    def get_company_profile(self, ticker: str) -> CompanyProfile | None: ...

    def upsert_company_profile(self, profile: CompanyProfile) -> CompanyProfile: ...

    def list_events(self, ticker: str, limit: int = 20) -> list[Event]: ...

    def upsert_events(self, ticker: str, events: list[Event]) -> list[Event]: ...

    def replace_events(self, ticker: str, events: list[Event]) -> list[Event]: ...

    def list_financial_summaries(self, ticker: str, limit: int = 8) -> list[FinancialSummary]: ...

    def upsert_financial_summaries(self, ticker: str, items: list[FinancialSummary]) -> list[FinancialSummary]: ...

    def list_prices(
        self,
        ticker: str,
        limit: int = 60,
        start_date: str | None = None,
        end_date: str | None = None,
    ) -> list[PriceDaily]: ...

    def upsert_prices(self, ticker: str, prices: list[PriceDaily]) -> list[PriceDaily]: ...

    def mark_synced(self, dataset: str, ticker: str, synced_at: str) -> None: ...

    def get_last_synced_at(self, dataset: str, ticker: str) -> str | None: ...

    def list_sync_state(self, ticker: str | None = None) -> list[dict[str, str]]: ...
